---

is_debug: true
listen:
  type: port
  bind_ip: 0.0.0.0
  port: 8080
db:
  host: localhost
  port: 5432
  user: pavel
  password: postgres
  name: wb_l0
  sslmode: disable
nats:
  streaming:
    cluster_id: test-cluster
    client_id: test-client
    subject: orders
    nats_url: nats://localhost:4222

